;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	forward-to-word
	kill-region
	kill-ring-save-line-or-region
	org-cycle
	org-force-self-insert
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	next-buffer
	))
